// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using PetshopApi.Infrastructure.Persistence;

#nullable disable

namespace PetshopApi.Infrastructure.Migrations
{
    [DbContext(typeof(PetShopContext))]
    [Migration("20260512115535_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PetshopApi.Domain.Entities.ItemOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<byte[]>("OrderId")
                        .IsRequired()
                        .HasColumnType("RAW(900)");

                    b.Property<byte[]>("ProductId")
                        .IsRequired()
                        .HasColumnType("RAW(900)");

                    b.Property<int>("Quantity")
                        .HasColumnType("NUMBER(10)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("DECIMAL(18, 2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("ItemOrders");
                });

            modelBuilder.Entity("PetshopApi.Domain.Entities.MedicalFile", b =>
                {
                    b.Property<byte[]>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(900)");

                    b.Property<string>("Allergies")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("NVARCHAR2(80)");

                    b.Property<string>("ChronicDiseases")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("NVARCHAR2(80)");

                    b.Property<DateTime>("LastVaccine")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Medicines")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("NVARCHAR2(80)");

                    b.Property<DateTime>("NextVaccine")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Obs")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.Property<byte[]>("PetId")
                        .IsRequired()
                        .HasColumnType("RAW(900)");

                    b.HasKey("Id");

                    b.HasIndex("PetId")
                        .IsUnique();

                    b.ToTable("MEDICAL_FILES", (string)null);
                });

            modelBuilder.Entity("PetshopApi.Domain.Entities.Order", b =>
                {
                    b.Property<byte[]>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(900)");

                    b.Property<DateTime?>("CrateDate")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("DeliveryAddress")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("NVARCHAR2(120)");

                    b.Property<decimal?>("DiscountApplied")
                        .HasColumnType("DECIMAL(18, 2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("DECIMAL(18, 2)");

                    b.Property<byte[]>("UserId")
                        .IsRequired()
                        .HasColumnType("RAW(900)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ORDERS", (string)null);
                });

            modelBuilder.Entity("PetshopApi.Domain.Entities.Pet", b =>
                {
                    b.Property<byte[]>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(900)");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)");

                    b.Property<string>("PhotoUrl")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("NVARCHAR2(120)");

                    b.Property<string>("Race")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)");

                    b.Property<byte[]>("UserId")
                        .IsRequired()
                        .HasColumnType("RAW(900)");

                    b.Property<decimal>("Weight")
                        .HasColumnType("DECIMAL(18, 2)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("PETS", (string)null);
                });

            modelBuilder.Entity("PetshopApi.Domain.Entities.PlanData", b =>
                {
                    b.Property<byte[]>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(900)");

                    b.Property<string>("Active")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("NVARCHAR2(1)");

                    b.Property<string>("Benefits")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)");

                    b.Property<int?>("ConsultationsMonth")
                        .HasColumnType("NUMBER(10)");

                    b.Property<decimal?>("MktDiscount")
                        .HasColumnType("DECIMAL(18, 2)");

                    b.Property<decimal>("MonthlyPrice")
                        .HasColumnType("DECIMAL(18, 2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)");

                    b.Property<byte[]>("SignatureId")
                        .IsRequired()
                        .HasColumnType("RAW(900)");

                    b.HasKey("Id");

                    b.HasIndex("SignatureId");

                    b.ToTable("PLAN_DATAS", (string)null);
                });

            modelBuilder.Entity("PetshopApi.Domain.Entities.Product", b =>
                {
                    b.Property<byte[]>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(900)");

                    b.Property<string>("Active")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("NVARCHAR2(1)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)");

                    b.Property<string>("ImgUrl")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("NVARCHAR2(180)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("NVARCHAR2(80)");

                    b.Property<decimal>("Price")
                        .HasColumnType("DECIMAL(18, 2)");

                    b.Property<string>("TargetSpecies")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)");

                    b.HasKey("Id");

                    b.ToTable("PRODUCTS", (string)null);
                });

            modelBuilder.Entity("PetshopApi.Domain.Entities.Query", b =>
                {
                    b.Property<byte[]>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(900)");

                    b.Property<string>("Obs")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.Property<byte[]>("PetId")
                        .IsRequired()
                        .HasColumnType("RAW(900)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)");

                    b.Property<DateTime?>("Time")
                        .HasColumnType("TIMESTAMP(7)");

                    b.HasKey("Id");

                    b.HasIndex("PetId");

                    b.ToTable("QUERIES", (string)null);
                });

            modelBuilder.Entity("PetshopApi.Domain.Entities.Signature", b =>
                {
                    b.Property<byte[]>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(900)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)");

                    b.Property<byte[]>("UserId")
                        .IsRequired()
                        .HasColumnType("RAW(900)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("SIGNATURES", (string)null);
                });

            modelBuilder.Entity("PetshopApi.Domain.Entities.User", b =>
                {
                    b.Property<byte[]>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(900)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("NVARCHAR2(80)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("NVARCHAR2(13)");

                    b.HasKey("Id");

                    b.ToTable("USERS", (string)null);
                });

            modelBuilder.Entity("PetshopApi.Domain.Entities.ItemOrder", b =>
                {
                    b.HasOne("PetshopApi.Domain.Entities.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PetshopApi.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("PetshopApi.Domain.Entities.MedicalFile", b =>
                {
                    b.HasOne("PetshopApi.Domain.Entities.Pet", "Pet")
                        .WithOne("MedicalFile")
                        .HasForeignKey("PetshopApi.Domain.Entities.MedicalFile", "PetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pet");
                });

            modelBuilder.Entity("PetshopApi.Domain.Entities.Order", b =>
                {
                    b.HasOne("PetshopApi.Domain.Entities.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PetshopApi.Domain.Entities.Pet", b =>
                {
                    b.HasOne("PetshopApi.Domain.Entities.User", "User")
                        .WithMany("Pets")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PetshopApi.Domain.Entities.PlanData", b =>
                {
                    b.HasOne("PetshopApi.Domain.Entities.Signature", "Signature")
                        .WithMany("Plans")
                        .HasForeignKey("SignatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Signature");
                });

            modelBuilder.Entity("PetshopApi.Domain.Entities.Query", b =>
                {
                    b.HasOne("PetshopApi.Domain.Entities.Pet", "Pet")
                        .WithMany("Queries")
                        .HasForeignKey("PetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pet");
                });

            modelBuilder.Entity("PetshopApi.Domain.Entities.Signature", b =>
                {
                    b.HasOne("PetshopApi.Domain.Entities.User", "User")
                        .WithMany("Signatures")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PetshopApi.Domain.Entities.Order", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("PetshopApi.Domain.Entities.Pet", b =>
                {
                    b.Navigation("MedicalFile")
                        .IsRequired();

                    b.Navigation("Queries");
                });

            modelBuilder.Entity("PetshopApi.Domain.Entities.Signature", b =>
                {
                    b.Navigation("Plans");
                });

            modelBuilder.Entity("PetshopApi.Domain.Entities.User", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("Pets");

                    b.Navigation("Signatures");
                });
#pragma warning restore 612, 618
        }
    }
}
